"""One builder per feather.ir/0 node type. Each takes keyword arguments and returns the plain dict the IR is made of.

Generated by packages/intent/scripts/generate.ts from packages/intent/src/spec.ts. Do not edit by hand.
Builders do not validate; feather_sdk.validate() does.
"""

from __future__ import annotations

from typing import Any, Literal, Required, TypedDict

Scalar = str | int | float | bool


class Expandable(TypedDict, total=False):
    """Detail on demand, behind "Why?". At least one entry."""

    why: str
    """The reason, in a sentence or two."""
    detail: str
    """Longer supporting detail."""


class ChoiceOption(TypedDict, total=False):
    """The options, at least two, ids unique."""

    id: Required[str]
    """Unique among the options."""
    label: Required[str]
    """The words for it."""
    description: str
    """One line more."""


class FormItem(TypedDict, total=False):
    """The questions, in order; ids unique within the form. Consecutive fields with the same group are shown together under it."""

    id: Required[str]
    """Unique among the fields; the key of its answer."""
    prompt: Required[str]
    """The question."""
    kind: Required[Literal["text", "long-text", "number", "email", "phone", "url", "date", "money"]]
    """What kind of value."""
    required: bool
    """An answer is needed to continue."""
    value: str | int | float
    """The current value, if any."""
    min: int | float
    """For number and money: the smallest accepted."""
    max: int | float
    """For number and money: the largest accepted."""
    maxLength: int
    """For text kinds: the longest accepted."""
    currency: str
    """For money: the currency."""
    group: str
    """A heading the field sits under, such as Schedule or Place."""


class Coordinates(TypedDict, total=False):
    """Latitude and longitude."""

    lat: Required[int | float]
    """Latitude."""
    lng: Required[int | float]
    """Longitude."""


class ProgressStep(TypedDict, total=False):
    """The plan, step by step."""

    id: Required[str]
    """Unique among the steps."""
    label: Required[str]
    """The step."""
    state: Required[Literal["pending", "active", "done", "blocked"]]
    """Where it stands."""


class Spend(TypedDict, total=False):
    """Money that will be spent."""

    amount: Required[int | float]
    """In the currency's major unit."""
    currency: Required[str]
    """ISO 4217 code."""


class Publish(TypedDict, total=False):
    """Something that will be made public."""

    audience: Required[str]
    """Who will see it."""


class Send(TypedDict, total=False):
    """Something that will be sent."""

    to: Required[str]
    """The recipient."""
    channel: str
    """How: email, SMS…"""


class Consent(TypedDict, total=False):
    """Permission the person grants."""

    to: Required[str]
    """Who receives it."""
    scope: Required[str]
    """What it covers."""


class Delete(TypedDict, total=False):
    """Something that will be deleted."""

    what: Required[str]
    """What."""


class Consequence(TypedDict, total=False):
    """What the act does, stated so it can be shown verbatim. At least one entry."""

    spend: Spend
    """Money that will be spent."""
    publish: Publish
    """Something that will be made public."""
    send: Send
    """Something that will be sent."""
    consent: Consent
    """Permission the person grants."""
    delete: Delete
    """Something that will be deleted."""
    statement: str
    """The consequence in the caller's own words."""


class ComparisonCriterion(TypedDict, total=False):
    """What they are compared on; each gives a value for every item."""

    label: Required[str]
    """The criterion."""
    values: Required[dict[str, Scalar]]
    """One value per compared node id."""


def _drop_none(value: Any) -> Any:
    if isinstance(value, dict):
        return {k: _drop_none(v) for k, v in value.items() if v is not None}
    if isinstance(value, (list, tuple)):
        return [_drop_none(v) for v in value]
    return value


def _node(type_: str, fields: dict[str, Any]) -> dict[str, Any]:
    return {"type": type_, **_drop_none(fields)}


def Text(
    *,
    id: str,
    text: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
) -> dict[str, Any]:
    """Plain words. One line with no decision renders as text, never a card.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        text: The words.
    """
    return _node(
        "Text",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "text": text},
    )


def Action(
    *,
    id: str,
    intent: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    label: str | None = None,
) -> dict[str, Any]:
    """Something the person can do.

    Replies: activate.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        label: The words for the act; defaults to the intent.
    """
    return _node(
        "Action",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "label": label},
    )


def Choice(
    *,
    id: str,
    intent: str,
    prompt: str,
    options: list[ChoiceOption],
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    multiple: bool | None = None,
    selected: list[str] | None = None,
) -> dict[str, Any]:
    """Pick one, or several, of a known set.

    Replies: choose (with value).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        prompt: The question.
        options: The options, at least two, ids unique.
        multiple: Several may be picked. Default false.
        selected: Option ids already picked: the preselection.
    """
    return _node(
        "Choice",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "prompt": prompt, "options": options, "multiple": multiple, "selected": selected},
    )


def Input(
    *,
    id: str,
    intent: str,
    prompt: str,
    kind: Literal["text", "long-text", "number", "email", "phone", "url", "date", "money"],
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    required: bool | None = None,
    value: str | int | float | None = None,
    min: int | float | None = None,
    max: int | float | None = None,
    maxLength: int | None = None,
    currency: str | None = None,
) -> dict[str, Any]:
    """A fact the caller does not have yet, asked of the person.

    Replies: submit (with value), skip.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        prompt: The question.
        kind: What kind of value.
        required: An answer is needed to continue.
        value: The current value, if any.
        min: For number and money: the smallest accepted.
        max: For number and money: the largest accepted.
        maxLength: For text kinds: the longest accepted.
        currency: For money: the currency.
    """
    return _node(
        "Input",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "prompt": prompt, "kind": kind, "required": required, "value": value, "min": min, "max": max, "maxLength": maxLength, "currency": currency},
    )


def Form(
    *,
    id: str,
    intent: str,
    fields: list[FormItem],
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    prompt: str | None = None,
    submitLabel: str | None = None,
) -> dict[str, Any]:
    """Several facts asked of the person together and sent with one act. Use it instead of separate Inputs when the caller acts on the answers at once, so no answer is lost because it was typed but not sent.

    Replies: submit (with value), skip.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        prompt: What the answers are for, in one line.
        fields: The questions, in order; ids unique within the form. Consecutive fields with the same group are shown together under it.
        submitLabel: The words for the one act that sends every answer; defaults to the intent.
    """
    return _node(
        "Form",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "prompt": prompt, "fields": fields, "submitLabel": submitLabel},
    )


def Price(
    *,
    id: str,
    amount: int | float,
    currency: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    label: str | None = None,
    period: Literal["once", "hour", "day", "week", "month", "year"] | None = None,
) -> dict[str, Any]:
    """An amount of money.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        amount: In the currency's major unit.
        currency: ISO 4217 code.
        label: What the amount is.
        period: How often it is charged. Default once.
    """
    return _node(
        "Price",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "amount": amount, "currency": currency, "label": label, "period": period},
    )


def Person(
    *,
    id: str,
    name: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    role: str | None = None,
    kind: Literal["human", "agent"] | None = None,
) -> dict[str, Any]:
    """A person or an agent.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        name: Their name.
        role: What they do here.
        kind: Default human.
    """
    return _node(
        "Person",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "name": name, "role": role, "kind": kind},
    )


def Date(
    *,
    id: str,
    value: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    until: str | None = None,
    label: str | None = None,
) -> dict[str, Any]:
    """A date, a date and time, or a range (ISO 8601).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        value: ISO 8601 date or date-time.
        until: The end of a range.
        label: What the date is.
    """
    return _node(
        "Date",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "value": value, "until": until, "label": label},
    )


def Location(
    *,
    id: str,
    name: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    address: str | None = None,
    coordinates: Coordinates | None = None,
) -> dict[str, Any]:
    """A place.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        name: Its name.
        address: Postal address.
        coordinates: Latitude and longitude.
    """
    return _node(
        "Location",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "name": name, "address": address, "coordinates": coordinates},
    )


def Status(
    *,
    id: str,
    state: Literal["idle", "working", "waiting", "done", "failed", "blocked"],
    label: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
) -> dict[str, Any]:
    """The state of something ongoing.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        state: Where it stands.
        label: What is in that state.
    """
    return _node(
        "Status",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "state": state, "label": label},
    )


def Progress(
    *,
    id: str,
    label: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    value: int | float | None = None,
    steps: list[ProgressStep] | None = None,
) -> dict[str, Any]:
    """How far along something is. No value means indeterminate.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        label: What is progressing.
        value: 0 to 1.
        steps: The plan, step by step.
    """
    return _node(
        "Progress",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "label": label, "value": value, "steps": steps},
    )


def Media(
    *,
    id: str,
    kind: Literal["image", "video", "audio", "document"],
    src: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    alt: str | None = None,
    transcript: str | None = None,
    captions: str | None = None,
    caption: str | None = None,
) -> dict[str, Any]:
    """An image, video, audio or document. Every medium carries its text equivalent.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        kind: What it is.
        src: Where it is (URL).
        alt: Required for image and video: what it shows.
        transcript: Required for audio; for video, this or captions.
        captions: URL of a caption track (WebVTT), for video.
        caption: A visible caption.
    """
    return _node(
        "Media",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "kind": kind, "src": src, "alt": alt, "transcript": transcript, "captions": captions, "caption": caption},
    )


def Confirmation(
    *,
    id: str,
    text: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    of: str | None = None,
) -> dict[str, Any]:
    """Something the person did took effect.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        text: What happened.
        of: The act this confirms.
    """
    return _node(
        "Confirmation",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "text": text, "of": of},
    )


def Warning(
    *,
    id: str,
    text: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    severity: Literal["caution", "danger"] | None = None,
    acknowledge: bool | None = None,
) -> dict[str, Any]:
    """A risk the person should know about.

    Replies: acknowledge.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        text: The risk.
        severity: Default caution.
        acknowledge: The person must acknowledge it.
    """
    return _node(
        "Warning",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "text": text, "severity": severity, "acknowledge": acknowledge},
    )


def Approval(
    *,
    id: str,
    intent: str,
    request: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    requester: str | None = None,
    scope: str | None = None,
    consequence: Consequence | None = None,
) -> dict[str, Any]:
    """A request for the person's authority: approve or reject.

    Replies: approve, reject (value optional).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        request: What is being asked.
        requester: The Person node asking.
        scope: What the approval covers.
        consequence: What the act does, stated so it can be shown verbatim. At least one entry.
    """
    return _node(
        "Approval",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "request": request, "requester": requester, "scope": scope, "consequence": consequence},
    )


def Recommendation(
    *,
    id: str,
    intent: str,
    summary: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    confidence: int | float | None = None,
    consequence: Consequence | None = None,
) -> dict[str, Any]:
    """What the caller recommends. It comes first; alternatives follow.

    Replies: accept.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        summary: The recommendation, in one line.
        confidence: 0 to 1.
        consequence: What the act does, stated so it can be shown verbatim. At least one entry.
    """
    return _node(
        "Recommendation",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "summary": summary, "confidence": confidence, "consequence": consequence},
    )


def PredictedChoice(
    *,
    id: str,
    intent: str,
    of: str,
    option: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    summary: str | None = None,
    confidence: int | float | None = None,
) -> dict[str, Any]:
    """The option the caller expects the person to pick in a Choice.

    Replies: accept, change (with value).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        of: The Choice node.
        option: The predicted option's id in that Choice.
        summary: Why, in one line.
        confidence: 0 to 1.
    """
    return _node(
        "PredictedChoice",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "of": of, "option": option, "summary": summary, "confidence": confidence},
    )


def Alternative(
    *,
    id: str,
    intent: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    label: str | None = None,
    for_: str | None = None,
    input: Literal["Price", "Date", "Text", "Location", "Person"] | None = None,
) -> dict[str, Any]:
    """Another way to go than the recommendation.

    Replies: choose (value optional).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        label: The words for it; defaults to the intent.
        for_: The node this is an alternative to; it must come before. Required when the experience has several Recommendations. (the IR field "for")
        input: The person supplies a value of this kind when choosing it.
    """
    return _node(
        "Alternative",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "label": label, "for": for_, "input": input},
    )


def Tradeoff(
    *,
    id: str,
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    of: str | None = None,
    summary: str | None = None,
    gains: list[str] | None = None,
    costs: list[str] | None = None,
) -> dict[str, Any]:
    """What one option gains and costs. At least one gain or cost.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        of: The option the tradeoff describes.
        summary: The tradeoff, in one line.
        gains: What it gains.
        costs: What it costs.
    """
    return _node(
        "Tradeoff",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "of": of, "summary": summary, "gains": gains, "costs": costs},
    )


def Autopick(
    *,
    id: str,
    intent: str,
    summary: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    of: str | None = None,
    undoWithin: int | None = None,
) -> dict[str, Any]:
    """A decision already made for the person, which they may keep or undo.

    Replies: keep, undo.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        summary: What was decided, in one line.
        of: The option decided on.
        undoWithin: Seconds the person has to undo. The caller, which owns time, refuses a late undo.
    """
    return _node(
        "Autopick",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "summary": summary, "of": of, "undoWithin": undoWithin},
    )


def Correction(
    *,
    id: str,
    intent: str,
    target: str,
    prompt: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    original: str | None = None,
) -> dict[str, Any]:
    """The person corrects something that was understood wrong.

    Replies: submit (with value).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        target: The node being corrected.
        prompt: The question.
        original: What was understood, in words.
    """
    return _node(
        "Correction",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "target": target, "prompt": prompt, "original": original},
    )


def Preference(
    *,
    id: str,
    intent: str,
    key: str,
    label: str,
    value: Scalar,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    options: list[Scalar] | None = None,
) -> dict[str, Any]:
    """A setting the person may change. Feather stores nothing; the reply goes back to the caller.

    Replies: set (with value).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        key: The caller's name for the setting.
        label: The words for it.
        value: The current value.
        options: The values allowed, when a fixed set.
    """
    return _node(
        "Preference",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "key": key, "label": label, "value": value, "options": options},
    )


def Comparison(
    *,
    id: str,
    items: list[str],
    criteria: list[ComparisonCriterion],
    intent: str | None = None,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
) -> dict[str, Any]:
    """Several nodes side by side on the same criteria.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        items: The compared node ids: at least two, each once.
        criteria: What they are compared on; each gives a value for every item.
    """
    return _node(
        "Comparison",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "items": items, "criteria": criteria},
    )


def IrreversibleAction(
    *,
    id: str,
    intent: str,
    consequence: Consequence,
    importance: Literal["high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    primary: bool | None = None,
    label: str | None = None,
    confirms: str | None = None,
) -> dict[str, Any]:
    """An act that cannot be undone: spending, publishing, sending, consent. Always explicit, never the default focus.

    Replies: confirm, cancel.

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        primary: This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
        label: The words for the act; defaults to the intent.
        consequence: What the act does, stated so it can be shown verbatim. At least one entry.
        confirms: The irreversible act this commits (any act marked reversible: false, such as a Recommendation, an Approval or a Choice). When an experience has a single IrreversibleAction, it confirms them implicitly.
    """
    return _node(
        "IrreversibleAction",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "primary": primary, "label": label, "consequence": consequence, "confirms": confirms},
    )


def ExploreMore(
    *,
    id: str,
    intent: str,
    importance: Literal["low", "normal", "high", "critical"] | None = None,
    reversible: bool | None = None,
    expandable: Expandable | None = None,
    label: str | None = None,
    topics: list[str] | None = None,
) -> dict[str, Any]:
    """More is available on request; the caller sends it when the person asks.

    Replies: expand (value optional).

    Args:
        id: Stable within the experience; replies and references use it.
        intent: What the human is doing here, in a few words. Required on act nodes.
        importance: How much it matters. Default normal; critical is never hidden behind expansion.
        reversible: Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
        expandable: Detail on demand, behind "Why?". At least one entry.
        label: The words for it; defaults to the intent.
        topics: What more is available.
    """
    return _node(
        "ExploreMore",
        {"id": id, "intent": intent, "importance": importance, "reversible": reversible, "expandable": expandable, "label": label, "topics": topics},
    )


__all__ = ["Text", "Action", "Choice", "Input", "Form", "Price", "Person", "Date", "Location", "Status", "Progress", "Media", "Confirmation", "Warning", "Approval", "Recommendation", "PredictedChoice", "Alternative", "Tradeoff", "Autopick", "Correction", "Preference", "Comparison", "IrreversibleAction", "ExploreMore"]
