import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"
import { DENSITY, ELEVATION, FONTS, MOTION, SHAPES, buildTheme, fontImports, migrateTokens } from "../src/index.mjs"

const here = import.meta.dirname
const read = (p: string) => fs.readFileSync(path.join(here, p), "utf8")
const json = (p: string) => JSON.parse(read(p))
/** The generated CSS minus its first line (the "Generated by" header, which names the tool). */
const body = (css: string) => css.slice(css.indexOf("\n") + 1)

describe("buildTheme", () => {
  // Golden files were written by the Feather 1.7.0 engine (qooe-core scripts/apply-brand.mjs). Moving the engine
  // into @aleeforoughi/feather-tokens must not change one byte of a theme.
  it.each([
    ["paper-sharp", () => json("../themes/paper-sharp.json").tokens],
    ["void-pill", () => json("../themes/void-pill.json").tokens],
    ["rich-brand", () => json("golden/rich-brand.json")],
  ])("writes the same %s theme as Feather 1.7.0", (name, tokens) => {
    const built = buildTheme(tokens())
    expect(built.ok).toBe(true)
    if (built.ok) expect(body(built.css)).toBe(body(read(`golden/${name}.1.7.0.css`)))
  })

  it("is deterministic", () => {
    const tokens = json("golden/rich-brand.json")
    expect(buildTheme(tokens)).toEqual(buildTheme(structuredClone(tokens)))
  })

  it("imports fonts through this package, so products need not install them", () => {
    const built = buildTheme(json("golden/rich-brand.json"))
    expect(built.ok && built.fonts).toContain('@import "@aleeforoughi/feather-tokens/fonts/poppins.css";')
    expect(built.ok && built.fonts).toContain('@import "@aleeforoughi/feather-tokens/fonts/figtree.css";')
  })

  it("ships a font stylesheet for every font it offers", () => {
    for (const family of Object.keys(FONTS)) {
      for (const spec of fontImports(family)) {
        const file = spec.replace("@aleeforoughi/feather-tokens/", "../")
        expect(fs.existsSync(path.join(here, file)), `${family}: ${file}`).toBe(true)
      }
    }
  })

  it("reports every problem in a broken brand", () => {
    const built = buildTheme({
      colors: { primary: "red", background: "#fff", surface: "#fff" },
      typography: { fontFamily: { display: "Comic Sans" } },
      shape: "blob",
      components: { button: { glow: true } },
    })
    expect(built.ok).toBe(false)
    if (!built.ok) {
      expect(built.problems).toEqual(
        expect.arrayContaining([
          "colors.primary must be a hex color",
          "colors.text must be a hex color",
          expect.stringContaining('typography.fontFamily.display "Comic Sans" is not in the foundation font set'),
          "shape must be one of sharp, soft, rounded, pill",
          "components.button.glow = true is not an allowed component token",
        ])
      )
    }
  })
})

describe("migrateTokens", () => {
  it("reads a qooe-tokens/1 brand (no schema field) as feather-tokens/2, keeping every field", () => {
    const v1 = json("golden/rich-brand.json")
    const result = migrateTokens(v1)
    expect(result).toEqual({ ok: true, from: "qooe-tokens/1", tokens: { ...v1, schema: "feather-tokens/2" } })
  })

  it("accepts an explicit qooe-tokens/1 and leaves feather-tokens/2 alone", () => {
    expect(migrateTokens({ schema: "qooe-tokens/1", colors: {} })).toMatchObject({ ok: true, from: "qooe-tokens/1" })
    expect(migrateTokens({ schema: "feather-tokens/2", colors: {} })).toMatchObject({ ok: true, from: "feather-tokens/2" })
  })

  it("rejects an unknown schema and non-objects", () => {
    expect(migrateTokens({ schema: "feather-tokens/9" })).toEqual({
      ok: false,
      problems: ['schema "feather-tokens/9" is not one Feather reads (qooe-tokens/1, feather-tokens/2)'],
    })
    expect(migrateTokens([])).toMatchObject({ ok: false })
    expect(buildTheme(null)).toMatchObject({ ok: false })
  })

  it("builds the same theme from either schema", () => {
    const v1 = json("golden/rich-brand.json")
    expect(buildTheme(v1)).toEqual(buildTheme({ ...v1, schema: "feather-tokens/2" }))
  })
})

describe("schema/feather-tokens-2.json", () => {
  const schema = json("../schema/feather-tokens-2.json")
  it("offers exactly the engine's axes and fonts", () => {
    expect(schema.properties.shape.enum).toEqual(Object.keys(SHAPES))
    expect(schema.properties.density.enum).toEqual(Object.keys(DENSITY))
    expect(schema.properties.elevation.enum).toEqual(Object.keys(ELEVATION))
    expect(schema.properties.motion.enum).toEqual(Object.keys(MOTION))
    expect(schema.properties.typography.properties.fontFamily.properties.body.enum).toEqual(Object.keys(FONTS))
  })
})
