// One builder per feather.ir/1 node type. Each takes an object of the node's fields and returns the typed IR node.
//
// Generated by packages/intent/scripts/generate.ts from packages/intent/src/spec.ts. Do not edit by hand.
// Builders do not validate; validate() does.
import type {
  TextNode,
  ActionNode,
  ChoiceNode,
  InputNode,
  FormNode,
  PriceNode,
  PersonNode,
  DateNode,
  LocationNode,
  StatusNode,
  ProgressNode,
  MediaNode,
  ConfirmationNode,
  WarningNode,
  ApprovalNode,
  RecommendationNode,
  PredictedChoiceNode,
  AlternativeNode,
  TradeoffNode,
  AutopickNode,
  CorrectionNode,
  PreferenceNode,
  ComparisonNode,
  IrreversibleActionNode,
  ExploreMoreNode,
} from "@aleeforoughi/feather-intent"

/** The fields of a node, without its `type` (the builder supplies that). Required fields are required. */
export type NodeInput<N extends { type: string }> = Omit<N, "type">

/** Drops `undefined` at every depth, so an optional field left unset is absent, as the IR means it. */
function dropUndefined(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(dropUndefined)
  if (typeof value === "object" && value !== null) return Object.fromEntries(Object.entries(value).filter(([, v]) => v !== undefined).map(([k, v]) => [k, dropUndefined(v)]))
  return value
}

function node<N extends { type: string }>(type: N["type"], fields: NodeInput<N>): N {
  return { type, ...(dropUndefined(fields) as object) } as N
}

/**
 * Plain words. One line with no decision renders as text, never a card.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.text The words.
 */
export const Text = (fields: NodeInput<TextNode>): TextNode => node("Text", fields)

/**
 * Something the person can do.
 *
 * Replies: activate.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.label The words for the act; defaults to the intent.
 */
export const Action = (fields: NodeInput<ActionNode>): ActionNode => node("Action", fields)

/**
 * Pick one, or several, of a known set.
 *
 * Replies: choose (with value).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.prompt The question.
 * @param fields.options The options, at least two, ids unique.
 * @param fields.multiple Several may be picked. Default false.
 * @param fields.selected Option ids already picked: the preselection.
 */
export const Choice = (fields: NodeInput<ChoiceNode>): ChoiceNode => node("Choice", fields)

/**
 * A fact the caller does not have yet, asked of the person.
 *
 * Replies: submit (with value), skip.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.prompt The question.
 * @param fields.kind What kind of value.
 * @param fields.required An answer is needed to continue.
 * @param fields.value The current value, if any.
 * @param fields.min For number and money: the smallest accepted.
 * @param fields.max For number and money: the largest accepted.
 * @param fields.maxLength For text kinds: the longest accepted.
 * @param fields.currency For money: the currency.
 */
export const Input = (fields: NodeInput<InputNode>): InputNode => node("Input", fields)

/**
 * Several facts asked of the person together and sent with one act. Use it instead of separate Inputs when the caller acts on the answers at once, so no answer is lost because it was typed but not sent.
 *
 * Replies: submit (with value), skip.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.prompt What the answers are for, in one line.
 * @param fields.fields The questions, in order; ids unique within the form. Consecutive fields with the same group are shown together under it.
 * @param fields.submitLabel The words for the one act that sends every answer; defaults to the intent.
 */
export const Form = (fields: NodeInput<FormNode>): FormNode => node("Form", fields)

/**
 * An amount of money.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.amount In the currency's major unit.
 * @param fields.currency ISO 4217 code.
 * @param fields.label What the amount is.
 * @param fields.period How often it is charged. Default once.
 */
export const Price = (fields: NodeInput<PriceNode>): PriceNode => node("Price", fields)

/**
 * A person or an agent.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.name Their name.
 * @param fields.role What they do here.
 * @param fields.kind Default human.
 */
export const Person = (fields: NodeInput<PersonNode>): PersonNode => node("Person", fields)

/**
 * A date, a date and time, or a range (ISO 8601).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.value ISO 8601 date or date-time.
 * @param fields.until The end of a range.
 * @param fields.label What the date is.
 */
export const Date = (fields: NodeInput<DateNode>): DateNode => node("Date", fields)

/**
 * A place.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.name Its name.
 * @param fields.address Postal address.
 * @param fields.coordinates Latitude and longitude.
 */
export const Location = (fields: NodeInput<LocationNode>): LocationNode => node("Location", fields)

/**
 * The state of something ongoing.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.state Where it stands.
 * @param fields.label What is in that state.
 */
export const Status = (fields: NodeInput<StatusNode>): StatusNode => node("Status", fields)

/**
 * How far along something is. No value means indeterminate.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.label What is progressing.
 * @param fields.value 0 to 1.
 * @param fields.steps The plan, step by step.
 */
export const Progress = (fields: NodeInput<ProgressNode>): ProgressNode => node("Progress", fields)

/**
 * An image, video, audio or document. Every medium carries its text equivalent.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.kind What it is.
 * @param fields.src Where it is (URL).
 * @param fields.alt Required for image and video: what it shows.
 * @param fields.transcript Required for audio; for video, this or captions.
 * @param fields.captions URL of a caption track (WebVTT), for video.
 * @param fields.caption A visible caption.
 */
export const Media = (fields: NodeInput<MediaNode>): MediaNode => node("Media", fields)

/**
 * Something the person did took effect.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.text What happened.
 * @param fields.of The act this confirms.
 */
export const Confirmation = (fields: NodeInput<ConfirmationNode>): ConfirmationNode => node("Confirmation", fields)

/**
 * A risk the person should know about.
 *
 * Replies: acknowledge.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.text The risk.
 * @param fields.severity Default caution.
 * @param fields.acknowledge The person must acknowledge it.
 */
export const Warning = (fields: NodeInput<WarningNode>): WarningNode => node("Warning", fields)

/**
 * A request for the person's authority: approve or reject.
 *
 * Replies: approve, reject (value optional).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.request What is being asked.
 * @param fields.requester The Person node asking.
 * @param fields.scope What the approval covers.
 * @param fields.consequence What the act does, stated so it can be shown verbatim. At least one entry.
 */
export const Approval = (fields: NodeInput<ApprovalNode>): ApprovalNode => node("Approval", fields)

/**
 * What the caller recommends. It comes first; alternatives follow.
 *
 * Replies: accept.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.summary The recommendation, in one line.
 * @param fields.confidence 0 to 1.
 * @param fields.consequence What the act does, stated so it can be shown verbatim. At least one entry.
 */
export const Recommendation = (fields: NodeInput<RecommendationNode>): RecommendationNode => node("Recommendation", fields)

/**
 * The option the caller expects the person to pick in a Choice.
 *
 * Replies: accept, change (with value).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.of The Choice node.
 * @param fields.option The predicted option's id in that Choice.
 * @param fields.summary Why, in one line.
 * @param fields.confidence 0 to 1.
 */
export const PredictedChoice = (fields: NodeInput<PredictedChoiceNode>): PredictedChoiceNode => node("PredictedChoice", fields)

/**
 * Another way to go than the recommendation.
 *
 * Replies: choose (value optional).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.label The words for it; defaults to the intent.
 * @param fields.for The node this is an alternative to; it must come before. Required when the experience has several Recommendations.
 * @param fields.input The person supplies a value of this kind when choosing it.
 */
export const Alternative = (fields: NodeInput<AlternativeNode>): AlternativeNode => node("Alternative", fields)

/**
 * What one option gains and costs. At least one gain or cost.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.of The option the tradeoff describes.
 * @param fields.summary The tradeoff, in one line.
 * @param fields.gains What it gains.
 * @param fields.costs What it costs.
 */
export const Tradeoff = (fields: NodeInput<TradeoffNode>): TradeoffNode => node("Tradeoff", fields)

/**
 * A decision already made for the person, which they may keep or undo.
 *
 * Replies: keep, undo.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.summary What was decided, in one line.
 * @param fields.of The option decided on.
 * @param fields.undoWithin Seconds the person has to undo. The caller, which owns time, refuses a late undo.
 */
export const Autopick = (fields: NodeInput<AutopickNode>): AutopickNode => node("Autopick", fields)

/**
 * The person corrects something that was understood wrong.
 *
 * Replies: submit (with value).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.target The node being corrected.
 * @param fields.prompt The question.
 * @param fields.original What was understood, in words.
 */
export const Correction = (fields: NodeInput<CorrectionNode>): CorrectionNode => node("Correction", fields)

/**
 * A setting the person may change. Feather stores nothing; the reply goes back to the caller.
 *
 * Replies: set (with value).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.key The caller's name for the setting.
 * @param fields.label The words for it.
 * @param fields.value The current value.
 * @param fields.options The values allowed, when a fixed set.
 */
export const Preference = (fields: NodeInput<PreferenceNode>): PreferenceNode => node("Preference", fields)

/**
 * Several nodes side by side on the same criteria.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.items The compared node ids: at least two, each once.
 * @param fields.criteria What they are compared on; each gives a value for every item.
 */
export const Comparison = (fields: NodeInput<ComparisonNode>): ComparisonNode => node("Comparison", fields)

/**
 * An act that cannot be undone: spending, publishing, sending, consent. Always explicit, never the default focus.
 *
 * Replies: confirm, cancel.
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.primary This node is the experience's main act: it gets the emphasis. Where focus starts is the composer's decision, never on an irreversible act. At most one per experience.
 * @param fields.label The words for the act; defaults to the intent.
 * @param fields.consequence What the act does, stated so it can be shown verbatim. At least one entry.
 * @param fields.confirms The irreversible act this commits (any act marked reversible: false, such as a Recommendation, an Approval or a Choice). When an experience has a single IrreversibleAction, it confirms them implicitly.
 */
export const IrreversibleAction = (fields: NodeInput<IrreversibleActionNode>): IrreversibleActionNode => node("IrreversibleAction", fields)

/**
 * More is available on request; the caller sends it when the person asks.
 *
 * Replies: expand (value optional).
 *
 * @param fields.id Stable within the experience; replies and references use it.
 * @param fields.intent What the human is doing here, in a few words. Required on act nodes.
 * @param fields.importance How much it matters. Default normal; critical is never hidden behind expansion.
 * @param fields.reversible Whether the effect can be undone. Default true; an act that states a consequence cannot be undone.
 * @param fields.expandable Detail on demand, behind "Why?". At least one entry.
 * @param fields.label The words for it; defaults to the intent.
 * @param fields.topics What more is available.
 */
export const ExploreMore = (fields: NodeInput<ExploreMoreNode>): ExploreMoreNode => node("ExploreMore", fields)
