// Feather branch — turns this copy of Feather into the project's own themed design system.
//
// Reads design/feather.json ({"components": ["button", "card", ...]}) chosen by the UI designer, keeps
// those atoms plus every atom they import, removes the rest (and their stories), writes the themed
// component sheet (src/foundation/BranchSheet.tsx, rendered by sheet.html) from the kept stories, and
// records the branch in feather.lock.json (Feather version, components, content hash of each atom) so
// QOOE can tell if a themed atom is edited later. Scaling a branch up = add names and run it again on a
// fresh Feather copy (or pull the atom from the Feather master).
//
// Deterministic: no network, no dependencies.
import crypto from "node:crypto"
import fs from "node:fs"
import path from "node:path"

const UI = "src/components/ui"
const read = (p) => fs.readFileSync(p, "utf8")
const exists = (p) => fs.existsSync(p)

function atomNames() {
  return fs
    .readdirSync(UI)
    .filter((f) => f.endsWith(".tsx") && !f.endsWith(".stories.tsx"))
    .map((f) => f.slice(0, -4))
    .sort()
}

/** Atoms every branch keeps: the foundation providers render toasts and tooltips. */
export const CORE_ATOMS = ["sonner", "tooltip"]

/** Atoms a component (and its stories) import, by alias or relative path. */
function importsOf(name) {
  const files = [`${name}.tsx`, `${name}.stories.tsx`].map((f) => path.join(UI, f)).filter(exists)
  const deps = new Set()
  for (const file of files) {
    const body = read(file)
    for (const m of body.matchAll(/from\s+["'](?:@\/components\/ui\/|\.\/)([a-z-]+)(?:\.tsx)?["']/g)) deps.add(m[1])
  }
  deps.delete(name)
  return [...deps]
}

export function closure(selected, available) {
  const keep = new Set()
  const visit = (n) => {
    if (keep.has(n) || !available.includes(n)) return
    keep.add(n)
    for (const dep of importsOf(n)) visit(dep)
  }
  for (const n of [...CORE_ATOMS, ...selected]) visit(n)
  return [...keep].sort()
}

function sheetSource(names) {
  const withStories = names.filter((n) => exists(path.join(UI, `${n}.stories.tsx`)))
  const id = (n) => `S_${n.replace(/-/g, "_")}`
  return `// Generated by scripts/feather-branch.mjs — the themed component sheet for this branch.
import { composeStories } from "@storybook/react-vite"
${withStories.map((n) => `import * as ${id(n)} from "@/components/ui/${n}.stories"`).join("\n")}

/** Stories that open an overlay on load (dialogs, sheets, popovers) would cover the whole sheet; their
 * surfaces use the card and popover tokens shown elsewhere on it. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function inPage(stories: Record<string, any>) {
  return Object.entries(stories).filter(([, Story]) => !Story.args?.defaultOpen)
}

const groups = [
${withStories.map((n) => `  { name: ${JSON.stringify(n)}, stories: inPage(composeStories(${id(n)})) },`).join("\n")}
].filter((group) => group.stories.length > 0)

export function BranchSheet() {
  return (
    <main className="mx-auto flex max-w-5xl flex-col gap-10 p-6 md:p-10">
      <header className="flex flex-col gap-1">
        <h1 className="font-heading text-3xl font-bold tracking-tight">Themed components</h1>
        <p className="text-muted-foreground text-sm">Every Feather component in this branch, in the project's theme.</p>
      </header>
      {groups.map((group) => (
        <section key={group.name} className="flex flex-col gap-3">
          <h2 className="text-muted-foreground text-xs font-semibold tracking-wide uppercase">{group.name}</h2>
          <div className="flex flex-wrap items-start gap-4">
            {group.stories.map(([storyName, Story]) => (
              <div key={storyName} className="flex min-w-40 flex-col gap-2">
                <span className="text-muted-foreground text-[11px]">{storyName}</span>
                <Story />
              </div>
            ))}
          </div>
        </section>
      ))}
    </main>
  )
}
`
}

function sha(p) {
  return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")
}

/**
 * Upgrade a branch to a newer Feather master in place: copy the newly selected components (and their
 * stories) plus any shared helpers (src/lib, src/foundation) the branch does not have yet. Components the
 * branch already has stay exactly as they are (their lock hashes prove they were never edited).
 */
export function upgradeFrom(masterDir, selection) {
  const masterUi = path.join(masterDir, UI)
  const pulled = []
  for (const n of selection) {
    if (exists(path.join(UI, `${n}.tsx`))) continue
    const from = path.join(masterUi, `${n}.tsx`)
    if (!exists(from)) return { ok: false, problems: [`${n} is not in the Feather master at ${masterDir}`] }
    fs.copyFileSync(from, path.join(UI, `${n}.tsx`))
    if (exists(path.join(masterUi, `${n}.stories.tsx`))) fs.copyFileSync(path.join(masterUi, `${n}.stories.tsx`), path.join(UI, `${n}.stories.tsx`))
    pulled.push(n)
  }
  for (const dir of ["src/lib", "src/foundation"]) {
    const src = path.join(masterDir, dir)
    if (!exists(src)) continue
    for (const f of fs.readdirSync(src)) {
      if (f === "Showcase.tsx" || f === "BranchSheet.tsx" || exists(path.join(dir, f))) continue
      fs.copyFileSync(path.join(src, f), path.join(dir, f))
    }
  }
  const version = JSON.parse(read(path.join(masterDir, "package.json"))).version
  return { ok: true, pulled, version }
}

export function runBranch({ selection, master = false, version } = {}) {
  const available = atomNames()
  const unknown = (selection ?? []).filter((n) => !available.includes(n))
  if (unknown.length > 0) return { ok: false, problems: [`Not Feather components: ${unknown.join(", ")}. Available: ${available.join(", ")}`] }
  const keep = selection && selection.length > 0 ? closure(selection, available) : available
  if (!master) {
    for (const n of available.filter((a) => !keep.includes(a))) {
      fs.rmSync(path.join(UI, `${n}.tsx`), { force: true })
      fs.rmSync(path.join(UI, `${n}.stories.tsx`), { force: true })
    }
    // The master's hand-made showcase uses every atom; a branch has its generated sheet instead.
    fs.rmSync("src/foundation/Showcase.tsx", { force: true })
    if (read("src/App.tsx").includes("Showcase")) {
      fs.writeFileSync("src/App.tsx", 'export default function App() {\n  return <main>QOOE is building this product.</main>\n}\n')
    }
  }
  fs.writeFileSync("src/foundation/BranchSheet.tsx", sheetSource(keep))
  const pkg = JSON.parse(read("package.json"))
  const lock = {
    feather: version ?? pkg.feather?.version ?? pkg.version,
    branchedAt: new Date().toISOString().slice(0, 10),
    components: keep,
    atoms: Object.fromEntries(keep.map((n) => [`${UI}/${n}.tsx`, sha(path.join(UI, `${n}.tsx`))])),
  }
  if (!master) fs.writeFileSync("feather.lock.json", `${JSON.stringify(lock, null, 2)}\n`)
  return { ok: true, kept: keep, removed: available.filter((a) => !keep.includes(a)) }
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)
if (isMain) {
  const master = process.argv.includes("--master")
  let selection = null
  if (!master && exists("design/feather.json")) {
    try {
      selection = JSON.parse(read("design/feather.json")).components ?? null
    } catch (err) {
      console.log(`design/feather.json is not valid JSON: ${err.message}`)
      process.exit(1)
    }
  }
  const upgradeAt = process.argv.indexOf("--upgrade-from")
  let version
  if (upgradeAt > 0 && selection) {
    const up = upgradeFrom(process.argv[upgradeAt + 1], selection)
    if (!up.ok) {
      console.log(`Feather upgrade failed:\n- ${up.problems.join("\n- ")}`)
      process.exit(1)
    }
    version = up.version
    console.log(`Feather upgrade to ${up.version}: pulled ${up.pulled.join(", ") || "nothing new"}.`)
  } else if (!master && exists("feather.lock.json") && selection) {
    const lock = JSON.parse(read("feather.lock.json"))
    const missing = selection.filter((n) => !lock.components.includes(n))
    if (missing.length > 0) {
      console.log(`This branch was cut without: ${missing.join(", ")}. Upgrade it from the Feather master: node scripts/feather-branch.mjs --upgrade-from <path to Feather master>.`)
      process.exit(1)
    }
  }
  const result = runBranch({ selection, master, ...(version ? { version } : {}) })
  if (!result.ok) {
    console.log(`Feather branch failed:\n- ${result.problems.join("\n- ")}`)
    process.exit(1)
  }
  console.log(`Feather branch: ${result.kept.length} components (${result.kept.join(", ")})${result.removed.length ? `; removed ${result.removed.length}` : ""}.`)
}
