#!/usr/bin/env node
// Writes Feather's fallback theme into css/foundation.css: the light block (:root) from themes/feather.json and the
// dark block (.dark) from themes/feather-dark.json, built by the same engine as any brand. A product that applies no
// brand therefore looks exactly like the feather reference theme. `--check` exits 1 when foundation.css has drifted
// from the themes (run by the package tests), without writing.
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { buildTheme } from "../src/engine.mjs"

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, "..")
const FILE = path.join(root, "css/foundation.css")
const START = "/* default-theme:start — generated by scripts/default-theme.mjs from themes/feather*.json; do not edit by hand. */"
const END = "/* default-theme:end */"

const declarations = (block) => Object.fromEntries([...block.matchAll(/^\s*(--[a-z0-9-]+):\s*([^;]+);/gm)].map((m) => [m[1], m[2]]))

function built(name) {
  const theme = JSON.parse(fs.readFileSync(path.join(root, "themes", `${name}.json`), "utf8"))
  const result = buildTheme(theme.tokens)
  if (!result.ok) throw new Error(`${name}: ${result.problems.join("; ")}`)
  return result.css
}

/** The variables of a built theme's :root:root block. */
function variables(name) {
  const css = built(name)
  return declarations(css.slice(css.indexOf(":root:root {"), css.indexOf("\n}\n")))
}

/** The variables of a built theme's AAA contrast block (empty when the theme already reaches AAA). */
function contrastVariables(name) {
  const css = built(name)
  const at = css.indexOf(':root:root[data-contrast="AAA"] {')
  return at < 0 ? {} : declarations(css.slice(at, css.indexOf("\n}", at)))
}

/** Sizes, durations, radii and elevation are the system's own (the base layer below); a theme block carries only what a
 * brand chooses here: colors, fonts and heading weight. An unlayered size here would beat [data-density] on <html>. */
const SYSTEM = /^--(spacing|control-|icon-slot|pad-|card-pad|dialog-pad|inset-|gap|group-gap|opacity-|elevation-|shadow-|duration-|ease-|motion-|radius-)/
const themed = (vars) => Object.fromEntries(Object.entries(vars).filter(([k]) => !SYSTEM.test(k)))

/** The generated region: every themed variable, in light and in dark (complete, so hygiene can check every pair). */
export function defaultThemeCss() {
  const light = themed(variables("feather"))
  const dark = themed(variables("feather-dark"))
  const lines = (vars) => Object.entries(vars).map(([k, v]) => `    ${k}: ${v};`).join("\n")
  // AAA (composer rule 10): the plan root carries data-contrast="AAA". The dark block names every variable the light
  // one does, so a light AAA value set on the plan root never shows in dark mode.
  const lightAAA = contrastVariables("feather")
  const darkAAA = contrastVariables("feather-dark")
  for (const k of Object.keys(lightAAA)) if (!(k in darkAAA)) darkAAA[k] = dark[k]
  const contrast =
    Object.keys(lightAAA).length + Object.keys(darkAAA).length === 0
      ? ""
      : `\n\n[data-contrast="AAA"] {\n${lines(lightAAA)}\n}\n\n.dark [data-contrast="AAA"],\n.dark[data-contrast="AAA"] {\n${lines(darkAAA)}\n}`
  return `${START}\n:root {\n${lines(light)}\n}\n\n.dark {\n${lines(dark)}\n}${contrast}\n${END}`
}

function rewrite(css) {
  const a = css.indexOf(START)
  const b = css.indexOf(END)
  if (a < 0 || b < 0) throw new Error("foundation.css has no default-theme markers")
  return css.slice(0, a) + defaultThemeCss() + css.slice(b + END.length)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const css = fs.readFileSync(FILE, "utf8")
  const next = rewrite(css)
  if (process.argv.includes("--check")) {
    if (next !== css) {
      console.error("css/foundation.css has drifted from themes/feather*.json: run node scripts/default-theme.mjs")
      process.exit(1)
    }
    console.log("foundation.css matches the feather themes")
  } else {
    fs.writeFileSync(FILE, next)
    console.log("foundation.css: default theme written from themes/feather.json and themes/feather-dark.json")
  }
}
