// Generated by scripts/feather-branch.mjs — the themed component sheet for this branch.
import { composeStories } from "@storybook/react-vite"
import * as S_accordion from "@/components/ui/accordion.stories"
import * as S_alert from "@/components/ui/alert.stories"
import * as S_avatar from "@/components/ui/avatar.stories"
import * as S_badge from "@/components/ui/badge.stories"
import * as S_breadcrumb from "@/components/ui/breadcrumb.stories"
import * as S_button from "@/components/ui/button.stories"
import * as S_card from "@/components/ui/card.stories"
import * as S_checkbox from "@/components/ui/checkbox.stories"
import * as S_dialog from "@/components/ui/dialog.stories"
import * as S_dropdown_menu from "@/components/ui/dropdown-menu.stories"
import * as S_field from "@/components/ui/field.stories"
import * as S_input from "@/components/ui/input.stories"
import * as S_label from "@/components/ui/label.stories"
import * as S_navigation_menu from "@/components/ui/navigation-menu.stories"
import * as S_popover from "@/components/ui/popover.stories"
import * as S_progress from "@/components/ui/progress.stories"
import * as S_radio_group from "@/components/ui/radio-group.stories"
import * as S_scroll_area from "@/components/ui/scroll-area.stories"
import * as S_select from "@/components/ui/select.stories"
import * as S_separator from "@/components/ui/separator.stories"
import * as S_sheet from "@/components/ui/sheet.stories"
import * as S_skeleton from "@/components/ui/skeleton.stories"
import * as S_sonner from "@/components/ui/sonner.stories"
import * as S_switch from "@/components/ui/switch.stories"
import * as S_table from "@/components/ui/table.stories"
import * as S_tabs from "@/components/ui/tabs.stories"
import * as S_textarea from "@/components/ui/textarea.stories"
import * as S_tooltip from "@/components/ui/tooltip.stories"

/** Stories that open an overlay on load (dialogs, sheets, popovers) would cover the whole sheet; their
 * surfaces use the card and popover tokens shown elsewhere on it. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function inPage(stories: Record<string, any>) {
  return Object.entries(stories).filter(([, Story]) => !Story.args?.defaultOpen)
}

const groups = [
  { name: "accordion", stories: inPage(composeStories(S_accordion)) },
  { name: "alert", stories: inPage(composeStories(S_alert)) },
  { name: "avatar", stories: inPage(composeStories(S_avatar)) },
  { name: "badge", stories: inPage(composeStories(S_badge)) },
  { name: "breadcrumb", stories: inPage(composeStories(S_breadcrumb)) },
  { name: "button", stories: inPage(composeStories(S_button)) },
  { name: "card", stories: inPage(composeStories(S_card)) },
  { name: "checkbox", stories: inPage(composeStories(S_checkbox)) },
  { name: "dialog", stories: inPage(composeStories(S_dialog)) },
  { name: "dropdown-menu", stories: inPage(composeStories(S_dropdown_menu)) },
  { name: "field", stories: inPage(composeStories(S_field)) },
  { name: "input", stories: inPage(composeStories(S_input)) },
  { name: "label", stories: inPage(composeStories(S_label)) },
  { name: "navigation-menu", stories: inPage(composeStories(S_navigation_menu)) },
  { name: "popover", stories: inPage(composeStories(S_popover)) },
  { name: "progress", stories: inPage(composeStories(S_progress)) },
  { name: "radio-group", stories: inPage(composeStories(S_radio_group)) },
  { name: "scroll-area", stories: inPage(composeStories(S_scroll_area)) },
  { name: "select", stories: inPage(composeStories(S_select)) },
  { name: "separator", stories: inPage(composeStories(S_separator)) },
  { name: "sheet", stories: inPage(composeStories(S_sheet)) },
  { name: "skeleton", stories: inPage(composeStories(S_skeleton)) },
  { name: "sonner", stories: inPage(composeStories(S_sonner)) },
  { name: "switch", stories: inPage(composeStories(S_switch)) },
  { name: "table", stories: inPage(composeStories(S_table)) },
  { name: "tabs", stories: inPage(composeStories(S_tabs)) },
  { name: "textarea", stories: inPage(composeStories(S_textarea)) },
  { name: "tooltip", stories: inPage(composeStories(S_tooltip)) },
].filter((group) => group.stories.length > 0)

export function BranchSheet() {
  return (
    <main className="mx-auto flex max-w-5xl flex-col gap-10 p-6 md:p-10">
      <header className="flex flex-col gap-1">
        <h1 className="font-heading text-3xl font-bold tracking-tight">Themed components</h1>
        <p className="text-muted-foreground text-sm">Every Feather component in this branch, in the project's theme.</p>
      </header>
      {groups.map((group) => (
        <section key={group.name} className="flex flex-col gap-3">
          <h2 className="text-muted-foreground text-xs font-semibold tracking-wide uppercase">{group.name}</h2>
          <div className="flex flex-wrap items-start gap-4">
            {group.stories.map(([storyName, Story]) => (
              <div key={storyName} className="flex min-w-40 flex-col gap-2">
                <span className="text-muted-foreground text-[11px]">{storyName}</span>
                <Story />
              </div>
            ))}
          </div>
        </section>
      ))}
    </main>
  )
}
